### GET todas las ciudades
GET http://127.0.0.1:8000/ruteo/ciudades/all

###
### GET destino por ID
GET http://127.0.0.1:8000/ruteo/destinos/7

###
### GET todos los destinos
GET https://ruteo-production.up.railway.app/ruteo/usuarios/all

###
### POST crear destino
POST https://ruteo-production.up.railway.app/ruteo/destinos/add
Content-Type: application/json

{
    "nom_destino": "Lima",
    "descripcion": "Hermoso lago para deportes acuaticos",
    "id_ciudad": 1,
    "tipo_destino": "natural",
    "imagen_url": "https://imagen.com/calima.jpg",
    "latitud": 3.9167,
    "longitud": -76.5,
    "activo": true
}

###
### PUT actualizar destino
PUT http://127.0.0.1:8000/ruteo/destinos/update/6
Content-Type: application/json

{
    "nom_destino": "machupicho",
    "descripcion": "Lago ideal para deportes acuaticos",
    "id_ciudad": 1,
    "tipo_destino": "natural",
    "imagen_url": "https://imagen.com/calima.jpg",
    "latitud": 3.9167,
    "longitud": -76.5,
    "activo": true
}


###
### DELETE borrar destino
DELETE http://127.0.0.1:8000/ruteo/viajes/borrar/1

###

### GET todos los restaurantes
GET http://127.0.0.1:8000/ruteo/restaurantes/all







#TOKENS_JWT



### AUTH - Register
POST http://127.0.0.1:8000/auth/register
Content-Type: application/json

{
  "nom_user": "pedro",
  "password": "12345",
  "rol": "user"
}

### AUTH - Login
POST http://127.0.0.1:8000/auth/login
Content-Type: application/json

{
  "nom_user": "pedro",
  "password": "12345"
}

### AUTH - Refresh
POST http://127.0.0.1:8000/auth/refresh
Authorization: Bearer TOKEN ACA

### AUTH - Logout
DELETE http://127.0.0.1:8000/auth/logout
Authorization: Bearer TOKEN ACA